version: '3.5'

services:
  web:
    build: .
    restart: always
    labels:
      traefik.enable: true
      traefik.http.routers.under-maintenance.priority: 2
      traefik.http.routers.under-maintenance.rule: Host(`coursetable.com`, `www.coursetable.com`, `beta.coursetable.com`)
      traefik.http.routers.under-maintenance.tls: true
      traefik.http.routers.under-maintenance.tls.certResolver: ctresolver
    networks:
      - traefik
      - default

networks:
  traefik:
    external: true
