version: '3.2'
services:
  umami:
    image: ghcr.io/mikecao/umami:postgresql-latest
    restart: always
    ports:
      - '4000:3000'
    environment:
      DATABASE_URL: postgresql://umami:umami@postgres:5432/umami
      DATABASE_TYPE: postgresql
      HASH_SALT: ${HASH_SALT}
    depends_on:
      - postgres
    labels:
      traefik.enable: true
      traefik.http.routers.coursetable.rule: Host(`umami.coursetable.com`)
      traefik.http.routers.coursetable.tls: true
      traefik.http.routers.coursetable.tls.certResolver: ctresolver
    networks:
      - traefik
      - default

  postgres:
    image: postgres:12-alpine
    restart: always
    ports:
      - '5432'
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - ./db/schema.database.sql:/docker-entrypoint-initdb.d/schema.database.sql

networks:
  traefik:
    external: true
