version: '3.5'

services:
  db:
    image: postgres
    container_name: ${FERRY_HOST?ferry_db}
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${FERRY_PASSWORD?ferry_password}
    networks:
      ferry:
        aliases:
          - ${FERRY_HOST?ferry_db}

networks:
  ferry:
    name: ferry
    driver: bridge
