version: '3.5'

services:
  db:
    container_name: ${DB_HOST?db}
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_ROOT_PASSWORD?password}
      POSTGRES_DB: ${DB_NAME?coursetable}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 0.5s
      timeout: 10s
      retries: 60
    volumes:
      - /home/app/db/data:/var/lib/postgresql/data
    networks:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL?pgadmin@coursetable.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD?password}
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    labels:
      traefik.enable: true
      traefik.http.routers.ct-pga.rule: Host(`pgadmin.coursetable.com`)
      traefik.http.routers.ct-pga.tls: true
      traefik.http.routers.ct-pga.tls.certResolver: ctresolver
    networks:
      - db
      - traefik

  pgbouncer:
    image: edoburu/pgbouncer
    container_name: ${DB_BOUNCER?pgbouncer}
    restart: always
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_ROOT_PASSWORD}@${DB_HOST}:${DB_PORT}/postgres
      AUTH_TYPE: scram-sha-256
      QUERY_WAIT_TIMEOUT: 600
      MAX_CLIENT_CONN: 5000
    ports:
      - '5432:5432'
    networks:
      - db

networks:
  traefik:
    external: true
  db:
    name: db
    driver: bridge