services:
  web:
    build: .
    restart: always
    container_name: under_maintenance
    labels:
      traefik.enable: true
      traefik.http.routers.under-maintenance.priority: 2
      traefik.http.routers.under-maintenance.rule: Host(`coursetable.com`) || Host(`api.coursetable.com`) || Host(`www.coursetable.com`)
      traefik.http.routers.under-maintenance.tls: true
      traefik.http.routers.under-maintenance.tls.certResolver: ctresolver
    networks:
      - traefik
      - under_maintenance
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  traefik:
    external: true
  under_maintenance:
    name: under_maintenance
    driver: bridge
