services:
  web:
    build: .
    restart: always
    container_name: under_maintenance
    labels:
      traefik.enable: true
      traefik.http.routers.under-maintenance.priority: 2
      traefik.http.routers.under-maintenance.rule: Host(`coursetable.com`, `api.coursetable.com`, `www.coursetable.com`)
      traefik.http.routers.under-maintenance.tls: true
      traefik.http.routers.under-maintenance.tls.certResolver: ctresolver
    networks:
      - traefik
      - under_maintenance

networks:
  traefik:
    external: true
  under_maintenance:
    name: under_maintenance
    driver: bridge
