version: '3.5'

services:
  mysql:
    image: mariadb:latest
    container_name: ${MYSQL_HOST?mysql_db}
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD?password}
    networks:
      - mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: ${MYSQL_HOST?mysql_db}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD?password}
    ports:
      - '8081:80'
    labels:
      traefik.enable: true
      traefik.http.routers.ct-pma.rule: Host(`pma.coursetable.com`)
      traefik.http.routers.ct-pma.tls: true
      traefik.http.routers.ct-pma.tls.certResolver: ctresolver
    networks:
      - traefik
      - mysql

networks:
  traefik:
    external: true
  mysql:
    name: mysql
    driver: bridge