version: '3.2'
services:
  mysql:
    image: mariadb:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD?password}
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - mysql
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD?password}
    ports:
      - '8081:80'
    labels:
      traefik.enable: true
      traefik.http.routers.ct-pma.rule: Host(`pma.coursetable.com`)
      traefik.http.routers.ct-pma.tls: true
      traefik.http.routers.ct-pma.tls.certResolver: ctresolver
    networks:
      - traefik
      - default

networks:
  traefik:
    external: true
